---
title: "Report"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
```

```{r}
players <- read_csv("player_stats.csv")
#This code takes the function read_csv and reads the player_stats.csv and then assigns it to the variable players.
```

```{r}
players
#This code calls the established variable
```

Idea 1: Visualize the data set!

```{r}
ggplot(data = players) +
  geom_histogram(aes(x = KDA), binwidth = .09) +
  labs(title = "Distribution of KDA", y = "Amount of Players", y = " ")
#This code uses ggplot to create a graph that shows the distribution of the players Kill's Death's and Assist's
```
```{r}
ggplot(data = players) +
  geom_histogram(aes(x = KD), binwidth = .09) +
  labs(title = "Distribution of KD", y = "Amount of Players", y = " ")
#This code is the same as the one above but instead shows the distribution of Kill's and Death's without assists
```





Idea 2: Maximum, minimum, and average KDA ratios.

```{r}
maximum_KDA_ratio <- players %>% 
  group_by(KDA) %>% 
  filter(KDA >= 1.6)
maximum_KDA_ratio
#This code filters the table to only show players that have a KDA higher then 1.6
```

```{r}
minimum_KDA_ratio <- players %>% 
  group_by(KDA) %>% 
  filter(KDA <= 0.8)
minimum_KDA_ratio
#This code then filters the table to show all players with a KDA lower then 0.8
```

```{r}
average_KDA_ratio <-
  players %>%
  group_by(KDA) %>% 
  summarise(players, average_KDA = mean(KDA))

average_KDA_ratio  
#This code first groups the players by their KDA then averages the KDA together
```


Idea 3: Who was the best player on each team?

```{r}
players %>%                                     
  arrange(desc(KDA)) %>% 
  group_by(Team) %>%
  slice(1)
#This code finds the best players of each team and shows their stats
```

Idea 4: Who played on the most maps. If there are several what is the KD efficiency of each player?

```{r}
players %>% 
  filter(Maps == 16) %>%
  summarize(Player, KD, Maps)
#This code shows which players played on the most amount of maps and what their KD was overall
```

Idea 5: What are the median values for KDA.

```{r}
players %>%
  group_by(KDA) 
  summarise(players, KDA_Median = median(KDA, na.rm = TRUE))
  
#This code finds the median of all the players KDA

```

